"""empty message

Revision ID: 5216b8bdba85
Revises: 22d2d1b075a6
Create Date: 2025-02-19 17:55:47.086274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5216b8bdba85'
down_revision = '22d2d1b075a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cargo_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumables', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cost_in_credits', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('crew', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('max_atmosphering_speed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pilots', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('films', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vehicle_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicle_pkey')
    )
    # ### end Alembic commands ###
