"""empty message

Revision ID: e78fa5dc0cb4
Revises: d05bd4c5b2a1
Create Date: 2025-02-20 12:14:00.603586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e78fa5dc0cb4'
down_revision = 'd05bd4c5b2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('starships',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('vehicles',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('films',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('films',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('residents',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('residents',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('films',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('films',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('vehicles',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('starships',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
